<?php
/**
 * BookingCreation
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * External Gateway API
 *
 * External Gateway API - This API provides the ability for Xplorie to find availability of attractions, to place a booking, reteieve a booking and cancel a booking with RMS provides via a common API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mark@datapointpartners.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BookingCreation Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BookingCreation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BookingCreation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rms_code' => 'string',
        'availability_id' => 'string',
        'product' => '\OpenAPI\Client\Model\ProductInfo',
        'customer_contact' => '\OpenAPI\Client\Model\Contact',
        'customer_types_required' => '\OpenAPI\Client\Model\BookingCustomerType[]',
        'note' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'rms_code' => null,
        'availability_id' => null,
        'product' => null,
        'customer_contact' => null,
        'customer_types_required' => null,
        'note' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rms_code' => 'rmsCode',
        'availability_id' => 'availabilityId',
        'product' => 'product',
        'customer_contact' => 'customerContact',
        'customer_types_required' => 'customerTypesRequired',
        'note' => 'note'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rms_code' => 'setRmsCode',
        'availability_id' => 'setAvailabilityId',
        'product' => 'setProduct',
        'customer_contact' => 'setCustomerContact',
        'customer_types_required' => 'setCustomerTypesRequired',
        'note' => 'setNote'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rms_code' => 'getRmsCode',
        'availability_id' => 'getAvailabilityId',
        'product' => 'getProduct',
        'customer_contact' => 'getCustomerContact',
        'customer_types_required' => 'getCustomerTypesRequired',
        'note' => 'getNote'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const RMS_CODE_FAIR_HARBOR = 'fair-harbor';
    const RMS_CODE_BOOKEO = 'bookeo';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRmsCodeAllowableValues()
    {
        return [
            self::RMS_CODE_FAIR_HARBOR,
            self::RMS_CODE_BOOKEO,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['rms_code'] = isset($data['rms_code']) ? $data['rms_code'] : null;
        $this->container['availability_id'] = isset($data['availability_id']) ? $data['availability_id'] : null;
        $this->container['product'] = isset($data['product']) ? $data['product'] : null;
        $this->container['customer_contact'] = isset($data['customer_contact']) ? $data['customer_contact'] : null;
        $this->container['customer_types_required'] = isset($data['customer_types_required']) ? $data['customer_types_required'] : null;
        $this->container['note'] = isset($data['note']) ? $data['note'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['rms_code'] === null) {
            $invalidProperties[] = "'rms_code' can't be null";
        }
        $allowedValues = $this->getRmsCodeAllowableValues();
        if (!is_null($this->container['rms_code']) && !in_array($this->container['rms_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'rms_code', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['availability_id'] === null) {
            $invalidProperties[] = "'availability_id' can't be null";
        }
        if ($this->container['product'] === null) {
            $invalidProperties[] = "'product' can't be null";
        }
        if ($this->container['customer_contact'] === null) {
            $invalidProperties[] = "'customer_contact' can't be null";
        }
        if ($this->container['customer_types_required'] === null) {
            $invalidProperties[] = "'customer_types_required' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rms_code
     *
     * @return string
     */
    public function getRmsCode()
    {
        return $this->container['rms_code'];
    }

    /**
     * Sets rms_code
     *
     * @param string $rms_code Internal rms code to identify which rms to send request to
     *
     * @return $this
     */
    public function setRmsCode($rms_code)
    {
        $allowedValues = $this->getRmsCodeAllowableValues();
        if (!in_array($rms_code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'rms_code', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['rms_code'] = $rms_code;

        return $this;
    }

    /**
     * Gets availability_id
     *
     * @return string
     */
    public function getAvailabilityId()
    {
        return $this->container['availability_id'];
    }

    /**
     * Sets availability_id
     *
     * @param string $availability_id The id provided in an availbility request to book against
     *
     * @return $this
     */
    public function setAvailabilityId($availability_id)
    {
        $this->container['availability_id'] = $availability_id;

        return $this;
    }

    /**
     * Gets product
     *
     * @return \OpenAPI\Client\Model\ProductInfo
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \OpenAPI\Client\Model\ProductInfo $product product
     *
     * @return $this
     */
    public function setProduct($product)
    {
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets customer_contact
     *
     * @return \OpenAPI\Client\Model\Contact
     */
    public function getCustomerContact()
    {
        return $this->container['customer_contact'];
    }

    /**
     * Sets customer_contact
     *
     * @param \OpenAPI\Client\Model\Contact $customer_contact customer_contact
     *
     * @return $this
     */
    public function setCustomerContact($customer_contact)
    {
        $this->container['customer_contact'] = $customer_contact;

        return $this;
    }

    /**
     * Gets customer_types_required
     *
     * @return \OpenAPI\Client\Model\BookingCustomerType[]
     */
    public function getCustomerTypesRequired()
    {
        return $this->container['customer_types_required'];
    }

    /**
     * Sets customer_types_required
     *
     * @param \OpenAPI\Client\Model\BookingCustomerType[] $customer_types_required customer_types_required
     *
     * @return $this
     */
    public function setCustomerTypesRequired($customer_types_required)
    {
        $this->container['customer_types_required'] = $customer_types_required;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string|null $note note
     *
     * @return $this
     */
    public function setNote($note)
    {
        $this->container['note'] = $note;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


